import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#f8fafc',
    paddingHorizontal: 20,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  backButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    backgroundColor: '#ffffff',
  },
  title: {
    color: '#111827',
    fontSize: 24,
    fontWeight: '500',
  },
  editButton: {
    height: 38,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: 19,
    backgroundColor: '#ccfbf1',
    paddingHorizontal: 14,
  },
  editText: {
    color: '#0f766e',
    fontSize: 14,
    fontWeight: '900',
  },
  profileCard: {
    alignItems: 'center',
    borderRadius: 18,
    backgroundColor: '#ffffff',
    marginTop: 24,
    padding: 24,
  },
  avatarWrap: {
    position: 'relative',
    width: 104,
    height: 104,
  },
  avatar: {
    width: 104,
    height: 104,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: '#7dd3fc',
    borderRadius: 52,
    backgroundColor: '#ecfeff',
    overflow: 'hidden',
  },
  avatarImage: {
    width: '100%',
    height: '100%',
  },
  cameraButton: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderRadius: 16,
    backgroundColor: '#0f766e',
  },
  name: {
    color: '#111827',
    fontSize: 22,
    fontWeight: '600',
    marginTop: 16,
  },
  subtitle: {
    color: '#64748b',
    fontSize: 14,
    fontWeight: '600',
    marginTop: 5,
  },
  detailsCard: {
    borderRadius: 18,
    backgroundColor: '#ffffff',
    marginTop: 18,
    paddingHorizontal: 16,
  },
  logoutButton: {
    height: 54,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    borderRadius: 14,
    backgroundColor: '#dc2626',
    marginTop: 36,
  },
  logoutText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '900',
  },
  detailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    paddingVertical: 16,
  },
  detailIcon: {
    width: 42,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    backgroundColor: '#ecfeff',
  },
  detailCopy: {
    flex: 1,
  },
  detailLabel: {
    color: '#94a3b8',
    fontSize: 12,
    fontWeight: '800',
  },
  detailValue: {
    color: '#111827',
    fontSize: 15,
    fontWeight: '500',
    marginTop: 4,
  },
  versionText: {
    color: '#94a3b8',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 18,
    textAlign: 'center',
  },
});

export default styles;
