import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#f8fafc',
  },
  scrollContent: {
    paddingHorizontal: 20,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  title: {
    color: '#111827',
    fontSize: 22,
    fontWeight: '400',
  },
  editButton: {
    height: 38,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1,
    borderRadius: 19,
    backgroundColor: '#ccfbf1',
    paddingHorizontal: 14,
  },
  editText: {
    color: '#0f766e',
    fontSize: 14,
    fontWeight: '900',
  },
  profileCard: {
    alignItems: 'center',
    borderRadius: 18,
    backgroundColor: '#ffffff',
    marginTop: 24,
    padding: 24,
  },
  avatarWrap: {
    position: 'relative',
    width: 104,
    height: 104,
  },
  avatar: {
    width: 104,
    height: 104,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: '#7dd3fc',
    borderRadius: 52,
    backgroundColor: '#ecfeff',
    overflow: 'hidden',
  },
  avatarImage: {
    width: '100%',
    height: '100%',
  },
  name: {
    color: '#111827',
    fontSize: 22,
    fontWeight: '400',
    marginTop: 16,
  },
  subtitle: {
    color: '#64748b',
    fontSize: 13,
    fontWeight: '400',
    marginTop: 5,
  },
  switchAccountButton: {
    minHeight: 70,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 16,
    backgroundColor: '#ffffff',
    marginTop: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  switchAccountIcon: {
    width: 42,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    backgroundColor: '#ecfeff',
  },
  switchAccountCopy: {
    flex: 1,
  },
  switchAccountTitle: {
    color: '#111827',
    fontSize: 15,
    fontWeight: '500',
  },
  switchAccountSubtitle: {
    color: '#94a3b8',
    fontSize: 12,
    fontWeight: '600',
    marginTop: 4,
  },
  detailsCard: {
    borderRadius: 18,
    backgroundColor: '#ffffff',
    marginTop: 18,
    paddingHorizontal: 16,
    paddingTop: 18,
  },
  addressCard: {
    minHeight: 74,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    borderRadius: 18,
    backgroundColor: '#ffffff',
    marginTop: 18,
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  sectionTitle: {
    color: '#64748b',
    fontSize: 16,
    fontWeight: '400',
    marginBottom: 2,
  },
  logoutButton: {
    height: 54,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    borderRadius: 14,
    backgroundColor: '#dc2626',
    marginTop: 36,
  },
  logoutText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '900',
  },
  detailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    paddingVertical: 16,
  },
  detailIcon: {
    width: 42,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    backgroundColor: '#ecfeff',
  },
  detailCopy: {
    flex: 1,
  },
  detailLabel: {
    color: '#94a3b8',
    fontSize: 12,
    fontWeight: '700',
  },
  detailValue: {
    color: '#111827',
    fontSize: 15,
    fontWeight: '400',
    marginTop: 4,
  },
  versionText: {
    color: '#94a3b8',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 18,
    textAlign: 'center',
  },
  switchSheetOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0, 0, 0, 0.42)',
  },
  switchSheet: {
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 20,
  },
  switchSheetHandle: {
    width: 44,
    height: 4,
    alignSelf: 'center',
    borderRadius: 3,
    backgroundColor: '#d1d5db',
    marginBottom: 16,
  },
  switchSheetAccountBox: {
    borderWidth: 1,
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  switchSheetAccountRow: {
    minHeight: 46,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  switchSheetAvatar: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 19,
    backgroundColor: '#ecfeff',
    overflow: 'hidden',
  },
  switchSheetAvatarImage: {
    width: '100%',
    height: '100%',
  },
  switchSheetAccountName: {
    flex: 1,
    fontSize: 15,
    fontWeight: '400',
  },
  switchSheetAddRow: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
    marginTop: 12,
  },
  switchSheetAddIcon: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 19,
    backgroundColor: '#071116',
  },
  switchSheetAddText: {
    flex: 1,
    fontSize: 15,
    fontWeight: '400',
  },
  metaText: {
    fontSize: 14,
    fontWeight: '700',
    marginTop: 16,
    textAlign: 'center',
  },
});

export default styles;
