import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#f8fafc',
  },
  content: {
    paddingHorizontal: 18,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  avatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
  },
  greeting: {
    flex: 1,
    color: '#111827',
    fontSize: 21,
    fontWeight: '500',
  },
  headerIcon: {
    width: 42,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
  },
  notificationButton: {
    position: 'relative',
  },
  notificationBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    minWidth: 22,
    height: 22,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#ffffff',
    borderRadius: 11,
    backgroundColor: '#dc2626',
    paddingHorizontal: 5,
  },
  notificationBadgeText: {
    color: '#ffffff',
    fontSize: 10,
    fontWeight: '900',
  },
  profileButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: '#7dd4fca9',
    borderRadius: 22,
    backgroundColor: '#ffffff',
  },
  profileImage: {
    width: '100%',
    height: '100%',
  },
  rewardSubtitle: {
    color: '#6b7280',
    fontSize: 16,
    lineHeight: 23,
    marginTop: 6,
  },
  enrollButton: {
    alignSelf: 'flex-start',
    borderRadius: 22,
    backgroundColor: '#ea580c',
    marginTop: 14,
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  enrollText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '800',
  },
  coin: {
    width: 86,
    height: 86,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 7,
    borderColor: '#fed7aa',
    borderRadius: 43,
    backgroundColor: '#f59e0b',
    marginLeft: 14,
  },
  coinText: {
    color: '#9a3412',
    fontSize: 22,
    fontWeight: '900',
  },
  sectionTitle: {
    color: '#111827',
    fontSize: 18,
    fontWeight: '600',
    marginTop: 32,
    marginBottom: 18,
  },
  horizontalList: {
    gap: 18,
    paddingRight: 18,
  },
  serviceCard: {
    width: 206,
    height: 146,
    overflow: 'hidden',
    borderRadius: 12,
    backgroundColor: '#ffffff',
    padding: 14,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 5,
  },
  serviceTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 8,
  },
  serviceCopy: {
    flex: 1,
  },
  serviceTitle: {
    color: '#111827',
    fontSize: 16,
    fontWeight: '800',
  },
  serviceSubtitle: {
    color: '#6b7280',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 5,
  },
  serviceIconWrap: {
    position: 'absolute',
    right: -6,
    bottom: -30,
    width: 128,
    height: 90,
    alignItems: 'center',
    justifyContent: 'center',
    borderTopLeftRadius: 70,
  },
  favouritesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 14,
  },
  favouriteCard: {
    width: '47.8%',
    minHeight: 92,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#d8b4fe',
    borderRadius: 12,
    backgroundColor: '#ffffff',
    padding: 10,
  },
  favouriteTitle: {
    color: '#111827',
    fontSize: 14,
    fontWeight: '800',
    lineHeight: 19,
    marginTop: 8,
    textAlign: 'center',
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 34,
    marginBottom: 16,
  },
  sectionTitleNoMargin: {
    color: '#111827',
    fontSize: 18,
    fontWeight: '600',
  },
  viewAll: {
    color: '#c2410c',
    fontSize: 15,
    fontWeight: '800',
  },
  skeletonCard: {
    width: 335,
    height: 136,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 12,
    backgroundColor: '#ffffff',
    padding: 10,
  },
  skeletonImage: {
    width: 126,
    height: 106,
    borderRadius: 12,
    backgroundColor: '#e5e7eb',
  },
  skeletonContent: {
    flex: 1,
    gap: 16,
    marginLeft: 14,
  },
  skeletonLineLarge: {
    height: 25,
    borderRadius: 14,
    backgroundColor: '#e5e7eb',
  },
  skeletonLineMedium: {
    width: '64%',
    height: 25,
    borderRadius: 14,
    backgroundColor: '#e5e7eb',
  },
  skeletonLineSmall: {
    width: '34%',
    height: 25,
    borderRadius: 14,
    backgroundColor: '#e5e7eb',
  },
  promoCard: {
    minHeight: 88,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 14,
    backgroundColor: '#ffedd5',
    padding: 18,
  },
  promoTitle: {
    color: '#111827',
    fontSize: 16,
    fontWeight: '800',
  },
  promoText: {
    color: '#6b7280',
    fontSize: 13,
    marginTop: 5,
  },
  placeholderCard: {
    alignItems: 'center',
    borderRadius: 18,
    backgroundColor: '#ffffff',
    marginTop: 28,
    paddingHorizontal: 22,
    paddingVertical: 36,
  },
  placeholderIcon: {
    width: 68,
    height: 68,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 34,
    backgroundColor: '#ccfbf1',
  },
  placeholderTitle: {
    color: '#111827',
    fontSize: 24,
    fontWeight: '900',
    marginTop: 18,
  },
  placeholderText: {
    color: '#64748b',
    fontSize: 15,
    fontWeight: '700',
    marginTop: 8,
    textAlign: 'center',
  },
  fab: {
    position: 'absolute',
    right: 26,
    width: 58,
    height: 58,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 29,
    backgroundColor: '#f8eadf',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 14,
    elevation: 7,
    zIndex: 16,
  },
  fabIcon: {
    fontWeight: '400',
  },
  fabMenuBackdrop: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 13,
  },
  fabMenu: {
    position: 'absolute',
    right: 26,
    width: 166,
    height: 166,
    flexDirection: 'row',
    flexWrap: 'wrap',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 16,
    backgroundColor: '#ffffff',
    padding: 10,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.16,
    shadowRadius: 22,
    elevation: 12,
    zIndex: 15,
  },
  fabMenuItem: {
    width: '50%',
    height: '50%',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  fabMenuText: {
    color: '#111827',
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
  },
  bottomNav: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    left: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    backgroundColor: '#ffffff',
    paddingTop: 10,
    paddingHorizontal: 12,
    borderTopWidth: 1,
    borderTopColor: 'rgba(0,0,0,0.03)',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: -8 },
    shadowOpacity: 0.06,
    shadowRadius: 16,
    elevation: 20,
  },
  navItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    borderRadius: 16,
    paddingVertical: 10,
    marginHorizontal: 1,
  },
  activeNavItem: {
    backgroundColor: '#fff3eb',
  },
  navText: {
    color: '#64748b',
    fontSize: 10,
    fontWeight: '600',
    marginTop: 2,
  },
  activeNavText: {
    color: '#ea580c',
    fontWeight: '800',
  },
  moreOverlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 20,
  },
  moreBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.28)',
  },
  moreSheet: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    left: 0,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    backgroundColor: '#f8fafc',
    paddingHorizontal: 18,
    paddingTop: 12,
  },
  sheetHandle: {
    width: 46,
    height: 5,
    alignSelf: 'center',
    borderRadius: 3,
    backgroundColor: '#cbd5e1',
    marginBottom: 16,
  },
  sheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sheetTitle: {
    color: '#111827',
    fontSize: 22,
    fontWeight: '900',
  },
  sheetCloseButton: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 18,
    backgroundColor: '#ffffff',
  },
  searchOverlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 30,
  },
  searchBackdrop: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: 'rgba(15, 23, 42, 0.28)',
  },
  searchPopup: {
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 18,
    backgroundColor: '#ffffff',
    marginHorizontal: 18,
    padding: 16,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.16,
    shadowRadius: 22,
    elevation: 12,
  },
  searchHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  searchTitle: {
    color: '#111827',
    fontSize: 20,
    fontWeight: '900',
  },
  searchCloseButton: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 17,
    backgroundColor: '#f8fafc',
  },
  searchInputWrap: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 12,
    backgroundColor: '#f8fafc',
    paddingHorizontal: 13,
  },
  searchInput: {
    flex: 1,
    color: '#111827',
    fontSize: 16,
    fontWeight: '600',
    paddingVertical: 10,
    marginLeft: 10,
  },
  clearSearchButton: {
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchHint: {
    color: '#64748b',
    fontSize: 13,
    lineHeight: 19,
    marginTop: 12,
  },
  companySwitcherOverlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 35,
  },
  companySwitcherBackdrop: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: 'rgba(15, 23, 42, 0.28)',
  },
  companySwitcherDropdown: {
    position: 'absolute',
    right: 18,
    left: 18,
    maxHeight: 300,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 18,
    backgroundColor: '#ffffff',
    paddingHorizontal: 16,
    paddingVertical: 14,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.16,
    shadowRadius: 22,
    elevation: 12,
  },
  companySwitcherHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  companySwitcherTitle: {
    color: '#111827',
    fontSize: 18,
    fontWeight: '900',
  },
  rewardTitle: {
    color: '#111827',
    fontSize: 21,
    fontWeight: '800',
  },
  companySwitcherSubtitle: {
    color: '#64748b',
    fontSize: 12,
    fontWeight: '600',
    marginTop: 2,
  },
  companySwitcherList: {
    gap: 8,
    paddingTop: 12,
  },
  companySwitcherRow: {
    minHeight: 56,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 14,
    backgroundColor: '#ffffff',
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  companySwitcherAvatar: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 18,
    backgroundColor: '#dbeafe',
  },
  companySwitcherAvatarText: {
    color: '#2563eb',
    fontSize: 13,
    fontWeight: '800',
  },
  companySwitcherCopy: {
    flex: 1,
  },
  companySwitcherName: {
    color: '#111827',
    fontSize: 13,
    fontWeight: '700',
  },
  companySwitcherMeta: {
    color: '#64748b',
    fontSize: 11,
    fontWeight: '500',
    marginTop: 2,
  },
  companySwitcherEmptyText: {
    color: '#64748b',
    fontSize: 14,
    fontWeight: '600',
    paddingVertical: 20,
    textAlign: 'center',
  },
});
export default styles
