import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: { paddingHorizontal: 6 },
    heroSection: { marginBottom: 20, padding: 16 },
    companyNameRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    companyMainTitle: { fontSize: 18, fontWeight: '500' },
    statusBadge: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 6, paddingVertical: 3, borderRadius: 6, gap: 4 },
    statusDot: { width: 5, height: 5, borderRadius: 2.5 },
    statusBadgeText: { fontSize: 10, fontWeight: '700', letterSpacing: 0.3 },
    companyIdText: { fontSize: 12, marginTop: 2 },
    locationRow: { flexDirection: 'row', alignItems: 'flex-start', marginTop: 6, gap: 2 },
    locationIcon: { fontSize: 12 },
    locationText: { fontSize: 12, fontWeight: '500' },
    sectionContainer: { borderRadius: 10, padding: 16, marginBottom: 14, borderWidth: 1 },
    sectionHeader: { fontSize: 13, fontWeight: '700', marginBottom: 12 },
    fieldGroup: { flexDirection: 'row', alignItems: 'center', gap: 10 },
    fieldIcon: {
        width: 34,
        height: 34,
        borderRadius: 17,
        borderWidth: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    fieldCopy: { flex: 1 },
    fieldLabel: { fontSize: 10, fontWeight: '600', letterSpacing: 0.4, marginBottom: 4 },
    fieldValue: { fontSize: 13, fontWeight: '400', lineHeight: 18 },
    divider: { height: 1, backgroundColor: '#e0e0e0', marginVertical: 10 },
});