import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        gap: 14,
        marginBottom: 18,
        paddingHorizontal: 6,
    },
    summaryCard: {
        backgroundColor: '#0D2137',
        borderColor: 'rgba(255,255,255,0.3)',
        borderRadius: 16,
        borderWidth: 1,
        elevation: 4,
        minHeight: 108,
        overflow: 'hidden',
        paddingHorizontal: 18,
        paddingVertical: 16,
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.18,
        shadowRadius: 12,
    },
    summaryDeco: {
        backgroundColor: 'rgba(255,255,255,0.03)',
        borderColor: 'rgba(255,255,255,0.07)',
        borderRadius: 50,
        borderWidth: 1,
        bottom: -22,
        height: 100,
        position: 'absolute',
        right: -18,
        width: 100,
    },
    summaryDecoSmall: {
        alignItems: 'center',
        backgroundColor: 'rgba(255,255,255,0.05)',
        borderColor: 'rgba(255,255,255,0.1)',
        borderRadius: 28,
        borderWidth: 1,
        bottom: 18,
        height: 55,
        justifyContent: 'center',
        position: 'absolute',
        right: 20,
        width: 55,
    },
    summaryLabel: {
        color: '#85B7EB',
        fontSize: 11,
        fontWeight: '500',
        letterSpacing: 0.7,
        lineHeight: 15,
        textTransform: 'uppercase',
    },
    summaryValue: {
        color: '#FFFFFF',
        fontSize: 25,
        fontWeight: '800',
        lineHeight: 32,
        marginTop: 6,
    },
    primaryBadge: {
        alignItems: 'center',
        alignSelf: 'flex-start',
        backgroundColor: 'rgba(255,255,255,0.07)',
        borderColor: 'rgba(255,255,255,0.1)',
        borderRadius: 10,
        borderWidth: 1,
        flexDirection: 'row',
        gap: 5,
        marginTop: 8,
        paddingHorizontal: 9,
        paddingVertical: 5,
    },
    primaryBadgeText: {
        color: '#85B7EB',
        fontSize: 10,
        fontWeight: '500',
        lineHeight: 13,
    },
    sectionTitleRow: {
        alignItems: 'center',
        flexDirection: 'row',
        gap: 7,
        marginTop: 2,
    },
    header: {
        fontSize: 16,
        fontWeight: '600',
        lineHeight: 21,
    },
    list: {
        gap: 12,
    },
    shareholderCard: {
        borderRadius: 8,
        borderWidth: 1,
        elevation: 1,
        paddingHorizontal: 15,
        paddingVertical: 15,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 6,
    },
    name: {
        fontSize: 15,
        fontWeight: '600',
        lineHeight: 20,
    },
    roleBadge: {
        alignSelf: 'flex-start',
        borderRadius: 7,
        borderWidth: 1,
        marginBottom: 14,
        marginTop: 6,
        paddingHorizontal: 9,
        paddingVertical: 4,
    },
    roleText: {
        fontSize: 10,
        fontWeight: '800',
        lineHeight: 13,
    },
    infoRow: {
        alignItems: 'center',
        flexDirection: 'row',
        marginTop: 7,
    },
    infoIcon: {
        width: 16,
    },
    infoText: {
        flex: 1,
        fontSize: 13,
        fontWeight: '500',
        lineHeight: 16,
    },
});